### PR TITLE
451 footer information

### PR DESCRIPTION
**Pull request by js-xc**

### CODE REVIEW

**Comment by jowerner** [comment]
In `config/xsl/loadreport/index.xsl`, please also replace 
```
 <xsl:with-param name="projectName" select="configuration/projectName" />
```
with
```
 <xsl:with-param name="projectName" select="$projectName" />
```
for consistency when calling the `head` template.

**Comment by jowerner** [comment]
Now that we started it, we should rework the `header` template in the same way, i.e. remove default parameter values and pass parameters explicitly in the load test report templates. WDYT?

**Review by jowerner — CHANGES_REQUESTED** [review]
See comments.

**Comment by js-xc** [comment]
Congratulations, you found the one file where I forgot to update the param for the `head` template :joy:

**Review by jowerner — APPROVED** [review]

**Pull request merged**
