### PR TITLE
#306 - Add hamburger menu

### PR DESCRIPTION
**Pull request by FabianHeydrich**
see #306 as a reference

### CODE REVIEW

**Review by rschwietzke — CHANGES_REQUESTED** [review]
Please see typical breaking points. 
https://testsigma.com/blog/css-breakpoints/

I am not sure what I used for the current change from large to small font... but one is likely a typicaly breakpoint.

**Comment by rschwietzke** [comment]
Besides that breakpoint feature, it looks ok. Please have the menu on the left side, also, we updated the menu too in a later XLT version, so it does not use superfish anymore and has different CSS, you might have to rebase your branch first.

**Comment by FabianHeydrich** [comment]
@rschwietzke I added breakpoints for the different screen sizes. Still open is the resizing of the Load Profile table. From waht I have seen so far the size of that table is fixed set in the HTML code

```
style="width: 1079.35px;"
```

**Comment by rschwietzke** [comment]
I will check and first rebase with the latest report state.

**Comment by rschwietzke** [comment]
What you see is the behavior of the table.js. There is not responsive version of a table, it will, sooner or later, turn into something horizontally scrollable.

**Comment by FabianHeydrich** [comment]
After the rebase I need to apply some changes to bring the hamburger menu back

**Pull request closed without merging**
